[header]
MAPBOX_TOKEN = "pk.eyJ1IjoicGVkcm9yZiIsImEiOiJjbG1pOGhkM2YybmdsM2RscGNxNW9mN25yIn0.VeO6-38K7x_86607eH7bsw"
DB_USER = "postgres.ahzokcumxpzwigghvlix"
DB_PASS = "sU4xx%23as%29bp%29F9e"
BRASIL_ABERTO_API_KEY = "mjPBys9CQvdkt5u3te0VXmmsqgHS1d8JFDkFKBrfrMlbLd5a6PYlroLHpsr0oM4F"